name: Bug report 🐛
description: |
  Something is broken and you have a reliable reproduction? Let us know here.
  For questions, please use the "Question" template.
labels:
  - needs triage
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        We prioritize issue with more details over those without.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Please provide one (or better yet, more) link as an example. The URL must be public accessible.
      placeholder: |
        - https://youtu.be/aqz-KE-bpKQ
        - https://www.youtube.com/watch?v=aqz-KE-bpKQ
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior.

        Tip: You can attach a video to show the steps required to reproduce this issue.
      placeholder: |
        1. In this environment...
        2. With this url...
        3. Go to '...'
        4. Click on '....'
        5. Scroll down to '....'
        6. See error...
  - type: textarea
    id: system
    attributes:
      label: System
      description: Please add system information.
      placeholder: |
        examples:
          - Device: PC, iPhone 14
          - OS: Window 11, Ubuntu 20.04, iOS 16.4
          - Node: 18.14.0
          - npm: 9.5.1
          - Browser: Chrome 114.0.5735.106
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images, videos or log files by clicking this area to highlight it and then dragging files in.
