name: New video provider 📺
description: Suggest a video provider.
labels:
  - needs triage
  - provider
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this video provider suggestion!

        We prioritize requests with more details over those without.

        If you wanted instead to report a bug with an existing video provider, please open a [bug](https://github.com/marcomontalbano/video-to-markdown/issues/new?template=bug_report.yml).
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: |
        The description of the video provider you are suggesting. Url to the provider's website is a plus.
        Any other information that you think is relevant.
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Please provide one (or better yet, more) link as an example. The URL must be public. Without a valid link, we can't add the provider, and the request will be closed.
      placeholder: |
        - https://youtu.be/aqz-KE-bpKQ
        - https://www.youtube.com/watch?v=aqz-KE-bpKQ
    validations:
      required: true
