name: Release

permissions:
  contents: write
  discussions: write

on:
  push:
    tags: ["v*"]

jobs:
  github_release:
    name: Trigger GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: pnpm 🧰
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Node 🧰
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install

      - name: Build 🛠
        run: pnpm --filter browser-extension build

      - name: Create a GitHub release 🎁
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'beta.') }}
          generate_release_notes: true
          discussion_category_name: Announcements
          files: |
            ./packages/browser-extension/dist-chrome.zip
            ./packages/browser-extension/dist-firefox.zip
